# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MgrsTool
                                 A QGIS plugin
 Capturar coordenadas, gerar grid e geometrias MGRS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-16
        copyright            : (C) 2025 by Thiago Kretzer Bechtold
        email                : bechtold.thiago@ime.eb.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MgrsTool class from file MgrsTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MgrsEbgeo import MgrsTool
    return MgrsTool(iface)
